main: mokkagnom.dasgesetz.Main
name: dasGesetz
version: 3.6.1
api-version: 1.20
author: MokkaGnom
description: Das Gesetz. Timber, EasyFarming, DeathChest, BlockLock, Home, Ping
commands:
   dgManager:
      description: Aktiviert/Deaktiviert den Command
      usage: /dgManager <command> <0/1>
      permission: dg.dgManagerPermission
      aliases:
      - dgm
   dasGesetz:
      description: Gibt das Gesetz im Chat aus
      usage: /dasGesetz [Artikel]
      permission: dg.dasGesetzPermission
      aliases:
      - dg
   weatherClear:
      description: Sets weather to clear
      usage: /weatherClear
      permission: dg.weatherClearPermission
      aliases:
      - wc
   coords:
      description: Return coordinates of player
      usage: /coords <Player>
      permission: dg.coordsPermission
      aliases:
      - co
   blockLock:
      description: Manages targeted lockable object
      usage: /blockLock <lock/unlock/addFriend/removeFriend/addGlobalFriend/removeGlobalFriend/listFriends/showMenu>
      permission: dg.blockLockPermission
      aliases:
      - bl
   home:
      description: Teleports/creates home
      usage: /home <tp/add/remove/list> <homeName>
      permission: dg.homePermission
      aliases:
      - h
   ping:
      description: Sets color of ping
      usage: /ping setColor <colorcode>
      permission: dg.pingPermission
      aliasses:
      - p
permissions:
   dg.dgManagerPermission:
      description: Allows a Player to use the Manager
      default: op
   dg.dasGesetzPermission:
      description: Allows a Player to use the Law command
      default: true
   dg.weatherClearPermission:
      description: Allows a Player to use the WeaterClear command
      default: true
   dg.coordsPermission:
      description: Allows a Player to use the Coords command
      default: op
   dg.timberPermission:
      description: Allows a Player to use timber
      default: true
   dg.deathChestPermission:
      description: Allows a Player to use/create deathChest
      default: true
   dg.deathChestByPassPermission:
      description: Allows a Player to use deathChest from everyone
      default: op
   dg.blockLockPermission:
      description: Allows a Player to use/create lockable chests, etc.
      default: true
   dg.blockLockByPassPermission:
      description: Allows a Player to use/create lockable chests, etc. from everyone
      default: op
   dg.homePermission:
      description: Allows a Player to use/create homes
      default: true
   dg.easyFarmingPermission:
      description: Allows a Player to use the plugin
      default: true
   dg.pingPermission:
      description: Allows a Player to use the ping
      default: true